apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: default
spec:
  selector:
    app: simple-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP