name: GitOps Deploy

on:
  push:
    branches: [ master, main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate YAML syntax
      run: |
        # Simple YAML validation
        python3 -c "import yaml; yaml.safe_load(open('simple-app/manifests/deployment.yaml'))"
        python3 -c "import yaml; yaml.safe_load(open('simple-app/application.yaml'))"
        
    - name: Success message
      run: |
        echo "✅ All YAML files are valid!"
        echo "🚀 ArgoCD will sync changes automatically"