name: Build and Deploy

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        echo "Setting up build environment..."
        
    - name: Lint and validate manifests
      run: |
        echo "Validating Kubernetes manifests..."
        # Check if files exist and are readable
        ls -la simple-app/manifests/
        ls -la simple-app/
        
    - name: Build validation
      run: |
        echo "Build completed successfully"
        echo "Deployment ready for GitOps sync"